# Generated by Django 5.2.8 on 2025-12-01 19:14

import auto_prefetch
import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
import uuid
import web.fields.models
import web.models.articles
import web.models.roles
import web.models.users
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядок сортировки')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытая категория')),
                ('is_hidden_for_users', models.BooleanField(default=False, verbose_name='Видна только модераторам')),
            ],
            options={
                'verbose_name': 'Категория форума',
                'verbose_name_plural': 'Категории форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, web.models.roles.PermissionsOverrideMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория ролей',
                'verbose_name_plural': 'Категории ролей',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Токен')),
                ('is_case_sensitive', models.BooleanField(default=True, verbose_name='Чувствителен к регистру')),
            ],
            options={
                'verbose_name': 'Использованный токен',
                'verbose_name_plural': 'Использованные токены',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('welcome', 'Приветственное сообщение'), ('new_post_reply', 'Ответ на пост'), ('new_thread_post', 'Новый пост'), ('new_article_revision', 'Правка статьи'), ('forum_mention', 'Упоминание на форуме')], verbose_name='Тип уведомления')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', web.fields.models.CITextField(error_messages={'unique': 'Пользователь с данным именем уже существует'}, max_length=150, unique=True, validators=[web.models.users.StrictUsernameValidator()], verbose_name='Имя пользователя')),
                ('wikidot_username', web.fields.models.CITextField(max_length=150, null=True, unique=True, validators=[web.models.users.StrictUsernameValidator()], verbose_name='Имя пользователя на Wikidot')),
                ('type', models.TextField(choices=[('normal', 'Обычный'), ('wikidot', 'Пользователь Wikidot'), ('system', 'Системный'), ('bot', 'Бот')], default='normal', verbose_name='Тип')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='-/users', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('api_key', models.CharField(blank=True, max_length=67, null=True, unique=True, verbose_name='Апи-ключ')),
                ('is_forum_active', models.BooleanField(default=True, verbose_name='Активирован форум')),
                ('forum_inactive_until', models.DateTimeField(null=True, verbose_name='Деактивировать форум до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('inactive_until', models.DateTimeField(null=True, verbose_name='Деактивировать до')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', web.fields.models.CITextField(default='_default', verbose_name='Категория')),
                ('name', web.fields.models.CITextField(verbose_name='Имя')),
                ('complete_full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('category', models.Value(':', output_field=web.fields.models.CITextField()), 'name'), output_field=web.fields.models.CITextField())),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('locked', models.BooleanField(default=False, verbose_name='Страница защищена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('media_name', models.TextField(default=uuid.uuid4, unique=True, verbose_name='Название папки с файлами в ФС-хранилище')),
                ('authors', models.ManyToManyField(related_name='authored_by', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('parent', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Родитель')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='web.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, web.models.roles.PermissionsOverrideMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_from', web.fields.models.CITextField(verbose_name='Ссылающаяся статья')),
                ('link_to', web.fields.models.CITextField(verbose_name='Целевая статья')),
                ('link_type', models.TextField(choices=[('include', 'Include'), ('link', 'Link')], verbose_name='Тип ссылки')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['link_from', 'link_to'], name='web_externa_link_fr_92155a_idx'), models.Index(fields=['link_type'], name='web_externa_link_ty_8f2d31_idx')],
                'constraints': [models.UniqueConstraint(fields=('link_from', 'link_to', 'link_type'), name='web_externallink_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('author', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('reply_to', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.forumpost', verbose_name='Ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Сообщение форума',
                'verbose_name_plural': 'Сообщения форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, web.models.roles.PermissionsOverrideMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор правки')),
                ('post', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumpost', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Версия сообщения форума',
                'verbose_name_plural': 'Версии сообщений форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядок сортировки')),
                ('is_for_comments', models.BooleanField(default=False, verbose_name='Отображать комментарии к статьям в этом разделе')),
                ('section', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumsection', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Раздел форума',
                'verbose_name_plural': 'Разделы форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Пришпилено')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('article', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья (если это комментарии)')),
                ('author', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumcategory', verbose_name='Раздел (если это тема)')),
            ],
            options={
                'verbose_name': 'Тема форума',
                'verbose_name_plural': 'Темы форума',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, web.models.roles.PermissionsOverrideMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(blank=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, verbose_name='Короткое название')),
                ('index', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Приоритет')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('votes_title', models.CharField(blank=True, verbose_name='Подпись группы голосов')),
                ('group_votes', models.BooleanField(default=False, verbose_name='Группировать голоса')),
                ('inline_visual_mode', models.CharField(choices=[('hidden', 'Скрыто'), ('badge', 'Бейдж'), ('icon', 'Иконка')], default='hidden', verbose_name='Режим отображения в имени')),
                ('profile_visual_mode', models.CharField(choices=[('hidden', 'Скрыто'), ('badge', 'Бейдж'), ('status', 'Статус')], default='hidden', verbose_name='Режим отображения в профиле')),
                ('color', web.fields.models.CSSColorField(default='#000000', verbose_name='Цвет')),
                ('icon', models.FileField(blank=True, upload_to='-/roles', validators=[web.models.roles.svg_file_validator], verbose_name='Иконка')),
                ('badge_text', models.CharField(blank=True, verbose_name='Текст бейджа')),
                ('badge_bg', web.fields.models.CSSColorField(default='#808080', verbose_name='Цвет бейджа')),
                ('badge_text_color', web.fields.models.CSSColorField(default='#ffffff', verbose_name='Цвет текста')),
                ('badge_show_border', models.BooleanField(default=False, verbose_name='Показывать границу')),
                ('permissions', models.ManyToManyField(blank=True, related_name='role_permissions_set', to='auth.permission', verbose_name='Разрешения')),
                ('restrictions', models.ManyToManyField(blank=True, related_name='role_restrictions_set', to='auth.permission', verbose_name='Запрещения')),
                ('category', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.rolecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['index'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='web.role', verbose_name='Роли'),
        ),
        migrations.CreateModel(
            name='RolePermissionsOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(blank=True, related_name='override_role_permissions_set', to='auth.permission')),
                ('restrictions', models.ManyToManyField(blank=True, related_name='override_role_restrictions_set', to='auth.permission')),
                ('role', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.role')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', web.fields.models.CITextField(verbose_name='Имя')),
                ('is_indexed', models.BooleanField(default=True, verbose_name='Индексируется поисковиками')),
                ('permissions_override', models.ManyToManyField(to='web.rolepermissionsoverride')),
            ],
            options={
                'verbose_name': 'Настройки категории',
                'verbose_name_plural': 'Настройки категорий',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, web.models.roles.PermissionsOverrideMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(verbose_name='Сокращение')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('headline', models.TextField(verbose_name='Подзаголовок')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='-/sites', verbose_name='Иконка')),
                ('domain', models.TextField(verbose_name='Домен для статей')),
                ('media_domain', models.TextField(verbose_name='Домен для файлов')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('domain',), name='web_site_domain_unique'), models.UniqueConstraint(fields=('slug',), name='web_site_slug_unique')],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_mode', models.TextField(choices=[('default', 'По умолчанию'), ('disabled', 'Отключено'), ('updown', 'Апвоуты'), ('stars', 'Звёзды')], default='default', verbose_name='Система рейтинга')),
                ('can_user_create_tags', models.TextField(choices=[('default', 'По умолчанию'), ('disabled', 'Запрещено'), ('enabled', 'Разрешено')], default='default', verbose_name='Может ли пользователь создавать теги')),
                ('category', auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.category')),
                ('site', auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.site')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TagsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер')),
                ('slug', models.TextField(unique=True, validators=[web.models.articles.TagsCategorySlugValidator()], verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Категория тегов',
                'verbose_name_plural': 'Категории тегов',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['name'], name='web_tagscat_name_19e56e_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='web_tagscategory_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=auto_prefetch.ForeignKey(default=web.models.articles.TagsCategory.get_or_create_default_tags_category, on_delete=django.db.models.deletion.CASCADE, to='web.tagscategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='UserNotificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('notification', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usernotification')),
                ('recipient', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья')),
                ('forum_thread', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='Ветка форума')),
                ('subscriber', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата голоса')),
                ('article', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='Статья')),
                ('role', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.role', verbose_name='Роль')),
                ('user', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stale_username', models.TextField(verbose_name='Имя на момент действия')),
                ('type', models.TextField(choices=[('vote', 'Оценка'), ('create_article', 'Страница создана'), ('edit_article', 'Страница отредактирована'), ('remove_article', 'Страница удалена'), ('add_forum_post', 'Новое сообщение форума'), ('edit_forum_post', 'Сообщение форума изменено'), ('remove_forum_post', 'Сообщение форума удалено'), ('change_profile_info', 'Информация профиля изменена')], verbose_name='Тип')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('origin_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Адрес')),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['user', 'origin_ip'], name='user_origin_ip_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('source', 'Изменение содержимого'), ('title', 'Изменение заголовка'), ('name', 'Изменение адреса страницы'), ('tags', 'Изменение тегов'), ('new', 'Создание страницы'), ('parent', 'Изменение родителя'), ('file_added', 'Добавление файлов'), ('file_deleted', 'Удаление файлов'), ('file_renamed', 'Переименование файлов'), ('votes_deleted', 'Сброс рейтинга'), ('authorship', 'Изменение авторства'), ('wikidot', 'Правка с Wikidot'), ('revert', 'Откат правки')], verbose_name='Тип')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('rev_number', models.PositiveIntegerField(verbose_name='Номер правки')),
                ('article', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья')),
                ('user', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в журнале изменений',
                'verbose_name_plural': 'Записи в журнале изменений',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'constraints': [models.UniqueConstraint(fields=('article', 'rev_number'), name='web_articlelogentry_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_plaintext', models.TextField(verbose_name='Текст статьи')),
                ('content_source', models.TextField(verbose_name='Исходный код статьи')),
                ('article', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Индекс для поиска по статьям',
                'verbose_name_plural': 'Индексы для поиска по статьям',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'constraints': [models.UniqueConstraint(fields=('article',), name='web_articlesearchindex_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='Исходник')),
                ('ast', models.JSONField(blank=True, null=True, verbose_name='AST-дерево статьи')),
                ('rendered', models.TextField(blank=True, null=True, verbose_name='Рендер статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('article', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='web.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Версия статьи',
                'verbose_name_plural': 'Версии статей',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['article', 'created_at'], name='web_article_article_eb894c_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название файла')),
                ('media_name', models.TextField(verbose_name='Название файла в ФС-хранилище')),
                ('mime_type', models.TextField(verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('article', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='Статья')),
                ('author', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='Автор файла')),
                ('deleted_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, удаливший файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['article', 'name'], name='web_file_article_c1ccbd_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'name', 'deleted_at'), name='web_file_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='user_email_ci_uniqueness'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['slug'], name='web_role_slug_06c2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['category'], name='web_role_categor_bd0076_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='web_categor_name_e51bae_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='web_category_unique'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='web_article_categor_7c81ec_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name'], name='web_article_name_1c14b5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['complete_full_name'], name='web_article_complet_ea3782_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='web_article_created_5524a8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['updated_at'], name='web_article_updated_20aa03_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='web_article_unique'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category', 'name'], name='web_tag_categor_b8c5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='web_tag_unique'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['article'], name='web_vote_article_a54b49_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='web_vote_unique'),
        ),
    ]
