# Generated by Django 5.2.8 on 2025-12-01 19:36

from django.db import migrations
from django.apps.registry import Apps


def create_default_roles(apps: Apps, schema_editor):
    Role = apps.get_model('web', 'Role')
    Role.objects.create(
        slug='everyone',
        index=0
    )
    Role.objects.create(
        slug='registered',
        index=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, migrations.RunPython.noop, atomic=True),
    ]
