# Generated by Django 5.2.8 on 2026-02-20 19:28

import web.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_create_built_in_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media_name',
            field=models.TextField(default=web.util.uuid4_str, unique=True, verbose_name='Название папки с файлами в ФС-хранилище'),
        ),
    ]
